surepharma/force-app/main/default/objects/Contact/recordTypes/Children.recordType-meta.xml
<RecordType>
    <fullName>Children</fullName>
    <active>true</active>
    <description>Eligible children</description>
    <label>Children</label>
</RecordType>

surepharma/force-app/main/default/objects/EmergencyCall__c/EmergencyCall__c.object-meta.xml
<CustomObject>
    <description>Records of emergency calls made to third-party emergency hotline after patch application.  Generated dynamically from callout to Google sheet Emergency Call Log (https://docs.google.com/spreadsheets/d/1ByVvhND1weHo1pQLEhmXv5texOd_O_1n3r7HC2MOobg/)</description>
    <label>Emergency Call</label>
    <nameField>
        <displayFormat>EC-{00000}</displayFormat>
        <label>Emergency Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emergency Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

surepharma/force-app/main/default/objects/EmergencyCall__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>EmergencyCalls</relationshipName>
    <type>Lookup</type>
</CustomField>

surepharma/force-app/main/default/objects/EmergencyCall__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

surepharma/force-app/main/default/objects/EmergencyCall__c/fields/LogId__c.field-meta.xml
<CustomField>
    <fullName>LogId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>External Id of emergency call from EmergencyCallLogMock</description>
    <externalId>true</externalId>
    <inlineHelpText>Generated from an external source</inlineHelpText>
    <label>LogId</label>
    <length>5</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

surepharma/force-app/main/default/classes/EmergencyCallLogCallout.cls
public class EmergencyCallLogCallout {

    /* Deprecated this for server-server connection via GoogleConnect class 

    public static HttpResponse makeGetCallout() {
        Http http = new Http();
        HttpRequest request = new HttpRequest();

        // TODO store some place
        String spreadsheetId = '1ByVvhND1weHo1pQLEhmXv5texOd_O_1n3r7HC2MOobg';

        // using Named Credential
        request.setEndpoint('callout:GoogleAPI/' + spreadsheetId + '/values/A1:Z1000?');  // grab entire sheet (would need to fix for larger datasets)
        request.setMethod('GET');

        HttpResponse response = http.send(request);

        if (response.getStatusCode() != 200) {
            System.debug('Failed to return expected response: ' + response.getStatusCode());
        }

        return response;
    }
    */

    public static HttpResponse sendRequest() {
        String token = GoogleConnect.getAccessToken();
        Http http = new Http();
        HttpRequest req = new HttpRequest();
        req.setHeader('Authorization', 'Bearer ' + token);
        String spreadsheetId = '1ByVvhND1weHo1pQLEhmXv5texOd_O_1n3r7HC2MOobg';
        req.setEndpoint('https://sheets.googleapis.com/v4/spreadsheets/' + spreadsheetId + '/values/A1:Z1000?');  // grab entire sheet (would need to fix for larger datasets)
        req.setMethod('GET');

        HttpResponse response = http.send(req);
        if (response.getStatusCode() != 200) {
            System.debug('Failed to return expected response: ' + response.getStatusCode());
        }

        return response;
    }

    public static void uploadEmergencyCalls(HttpResponse resp) {
        Map<String,Object> results = (Map<String,Object>) JSON.deserializeUntyped(resp.getBody());
        List<Object> values = (List<Object>) results.get('values');
        List<Object> headers = (List<Object>) values[0];

        Map<String,Integer> fieldIndex = new Map<String,Integer>();
        for (Integer i=0; i < headers.size(); i++) {
            fieldIndex.put(
                (String) headers[i], i
            );
        }

        Id childRtId = ContactTriggerHelper.getContactRecordTypeId('Children');
        Map<Id,Id> cMap = new Map<Id,Id>();
        for (Contact c : [SELECT Id, OwnerId FROM Contact WHERE RecordTypeId=:childRtId]) {
            cMap.put(c.Id, c.OwnerId);
        }

        List<EmergencyCall__c> ecalls = new List<EmergencyCall__c>();
        for (Integer i=1; i < values.size(); i++) {
            List<Object> row = (List<Object>) values[i];
            String logId = (String) row[fieldIndex.get('Id')];
            Date eDate = Date.valueOf(
                (String) row[fieldIndex.get('Date')]
            );
            Id contactId = (String) row[fieldIndex.get('ContactId')];
            String description = (String) row[fieldIndex.get('Description')];

            EmergencyCall__c ec = new EmergencyCall__c(
                LogId__c = logId,
                Date__c = eDate,
                Contact__c = contactId,
                Description__c = description,
                OwnerId = cMap.get(contactId)
            );
            ecalls.add(ec);
        }

        upsert ecalls LogId__c;
    }

    @AuraEnabled
    public static String clientHandler() {
        String value = 'Success';
        try {
            HttpResponse resp = sendRequest();
            uploadEmergencyCalls(resp);
        } catch (Exception e) {
            value = e.getMessage();
        }
        return value;
    }
}