surepharma/force-app/main/default/objects/Contact/fields/Follow_Up_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Datetime__c</fullName>
    <inlineHelpText>Set from related &quot;Follow Up&quot; event</inlineHelpText>
    <label>Follow Up Datetime</label>
    <type>DateTime</type>
</CustomField>

surepharma/force-app/main/default/objects/Contact/fields/Follow_Up_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Apex-generated: Patch_Applied_Datetime__c + 48 hours.  Used to auto-toggle Stage__c to &quot;Follow-up&quot;.</description>
    <inlineHelpText>Set by apex formula: &quot;Patch Applied Datetime&quot; plus 48 hours</inlineHelpText>
    <label>Follow Up Eligible</label>
    <type>Checkbox</type>
</CustomField>

surepharma/force-app/main/default/objects/Contact/fields/Patch_Applied_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Patch_Applied_Datetime__c</fullName>
    <description>Apex-generated from &quot;Patch Appointment&quot; event</description>
    <inlineHelpText>Set from related &quot;Patch Appointment&quot; event</inlineHelpText>
    <label>Patch Applied Datetime</label>
    <type>DateTime</type>
</CustomField>

surepharma/force-app/main/default/objects/Contact/fields/Pediatrician__c.field-meta.xml
<CustomField>
    <fullName>Pediatrician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Apex-generated</description>
    <label>Pediatrician</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Pediatrician</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

surepharma/force-app/main/default/objects/Contact/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <defaultValue>&quot;Screening&quot;</defaultValue>
    <inlineHelpText>Process path for eligible child in study</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Screening</fullName>
                <default>true</default>
                <label>Screening</label>
            </value>
            <value>
                <fullName>Appointment</fullName>
            </value>
            <value>
                <fullName>Patch Applied</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

surepharma/force-app/main/default/objects/Contact/recordTypes/Children.recordType-meta.xml
<RecordType>
    <fullName>Children</fullName>
    <active>true</active>
    <description>Eligible children</description>
    <label>Children</label>
</RecordType>

surepharma/force-app/main/default/classes/EventTriggerHelper.cls
public class EventTriggerHelper {
    public static Map<Id,Contact> getEligibleChildContacts() {
        Id childRtId = ContactTriggerHelper.getContactRecordTypeId('Children');

        Contact[] contacts = [
            SELECT Id, Pediatrician__c, Stage__c, Phone, Patch_Applied_Datetime__c, Follow_Up_Datetime__c, Follow_Up_Eligible__c
            FROM Contact 
            WHERE RecordTypeId=:childRtId
        ];

        Map<Id,Contact> cMap = new Map<Id,Contact>();
        if (contacts.size() > 0) {
            for (Contact c: contacts) {
                cMap.put(c.Id, c);
            }
        }
        return cMap;
    }

    public static Map<Id,Account> getPediatricianAccounts() {
        Account[] accts = [SELECT Id, BillingAddress FROM Account WHERE Type='Pediatrician'];

        Map<Id,Account> aMap = new Map<Id,Account>();
        if (accts.size() > 0) {
            for (Account a: accts) {
                aMap.put(a.Id, a);
            }
        }
        return aMap;
    }
}